//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal1
{
    using System;
    using System.Collections.Generic;

    public class Expenditure
    {
        public Nullable<System.DateTime> future_date { get; set; }
        public Nullable<System.DateTime> real_date { get; set; }
        public int id { get; set; }
        public int amount { get; set; }
        public string purpose { get; set; }
        public string way_of_payment { get; set; }
        public string Receives { get; set; }
        public Nullable<int> status { get; set; }

        public virtual Status Status1 { get; set; }
    }
}
