//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGmach.Entity.Models
{
    using System;
    using System.Collections.Generic;

    public class Expenditure
    {
      
        public DateTime Date { get; set; }
        public int Id { get; set; }
        public int Amount { get; set; }
        public string Purpose { get; set; }
        public string Way_of_payment { get; set; }
        public string Receives { get; set; }
        public string NameStatus { get; set; }
        public Status Status { get; set; }
          
    
    }
}
