//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal1
{
    using System;
    using System.Collections.Generic;

    public   class Management_status
    {
         public Management_status()
        {
            this.Users = new HashSet<User>();
        }

        public int Id { get; set; }
        public string name { get; set; }
        public string Color { get; set; }

         public virtual ICollection<User> Users { get; set; }
    }
}
