//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGmach.Entity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Management_status
    {

        [Key]
        public string NameManagement_status { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }

        public List<User> Users { get; }=new List<User>();
        public List<Loan> Loans { get;}=new List<Loan>();

        
    }
}
