//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal1
{
    using System;
    using System.Collections.Generic;

    public   class Status
    {
         public Status()
        {
            this.Expenditures = new HashSet<Expenditure>();
            this.Funds = new HashSet<Fund>();
            this.withdrawings = new HashSet<withdrawing>();
        }

        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }

         public virtual ICollection<Expenditure> Expenditures { get; set; }
         public virtual ICollection<Fund> Funds { get; set; }
         public virtual ICollection<withdrawing> withdrawings { get; set; }

    }
}
