using System.Collections.Generic;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGmach.Entity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class Status
    {
       [Key]
       public string NameStatus { get; set; }
       public string Description { get; set; }
       public List<Expenditure> Expenditures { get;}=new List<Expenditure>();
       public List<Income> Incomes { get;}=new List<Income>();
       public List<Repayment> Repayments { get; }=new List<Repayment>();
       public List<withdrawing> Withdrawings { get;}=new List<withdrawing>();
       public List<User> Users { get;}=new List<User>();
    }
}
