//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SGmach.Entity.Models
{
    using System;
    using System.Collections.Generic;


    public  class User_in_fund
    {
        public int User_in_fundId { get; set; }
        public string GmachId { get; set; }="shavet hchim";
        public DateTime date_join { get; set; }
        public int balance { get; set; }
        public int FundId { get; set; }

        public List<Deposit> Deposits { get; }=new List<Deposit>();
        public List<withdrawing> Withdrawings { get; }=new List<withdrawing>();

        public  Fund Fund { get; set; }
        public int UserId { get; set; }
        public  User User { get; set; }
    }
}
