//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal1
{
    using System;
    using System.Collections.Generic;

    public   class withdrawing
    {
        public int UserID { get; set; }
        public int FundID { get; set; }
        public int Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> sStatus { get; set; }
        public int Id { get; set; }

        public virtual Status Status1 { get; set; }
    }
}
