//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int Id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> fund_id { get; set; }
        public string type { get; set; }
        public Nullable<int> status { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Fund Fund { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual User User { get; set; }
    }
}
