//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_in_fund
    {
        public int userID { get; set; }
        public int fundID { get; set; }
        public Nullable<System.DateTime> date_join { get; set; }
        public Nullable<int> balance { get; set; }
    
        public virtual Fund Fund { get; set; }
        public virtual User User { get; set; }
    }
}
