//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal1
{
    using System;
    using System.Collections.Generic;
    
    public partial class withdrawing
    {
        public int userID { get; set; }
        public int fundID { get; set; }
        public int amount { get; set; }
        public Nullable<System.DateTime> future_date { get; set; }
        public Nullable<System.DateTime> real_date { get; set; }
        public Nullable<int> status { get; set; }
        public string status_reason { get; set; }
        public int id { get; set; }
    
        public virtual Status Status1 { get; set; }
    }
}
